// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Turrist_agent.Data;

namespace Turrist_agent.Migrations
{
    [DbContext(typeof(Turrist_agentContext))]
    partial class Turrist_agentContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Turrist_agent.Moduls.Dolzhnosti", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name_dolzhnosti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obyazannosti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Oklad")
                        .HasColumnType("int");

                    b.Property<long?>("SotrudnikiID")
                        .HasColumnType("bigint");

                    b.Property<string>("Trebovaniya")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("SotrudnikiID");

                    b.ToTable("Dolzhnosti");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Dop_uslugi", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Cena")
                        .HasColumnType("int");

                    b.Property<string>("Naimenovanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opisanie")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Dop_uslugi");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Klienti", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Data_rozhdeniya")
                        .HasColumnType("datetime2");

                    b.Property<string>("FIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PutevkiID")
                        .HasColumnType("bigint");

                    b.Property<string>("adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("pass_dannie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PutevkiID");

                    b.ToTable("Klienti");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Oteli", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Kolvo_zvezd")
                        .HasColumnType("int");

                    b.Property<string>("Naimenovanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Strana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("gorod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("kontact_Lico")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Oteli");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Putevki", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("data_nachala")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("data_okonchaniya")
                        .HasColumnType("datetime2");

                    b.Property<int>("kod_klienta")
                        .HasColumnType("int");

                    b.Property<int>("kod_sotrudnika")
                        .HasColumnType("int");

                    b.Property<int>("kod_uslugi_1")
                        .HasColumnType("int");

                    b.Property<int>("kod_uslugi_2")
                        .HasColumnType("int");

                    b.Property<int>("kod_uslugi_3")
                        .HasColumnType("int");

                    b.Property<int>("kod_vida")
                        .HasColumnType("int");

                    b.Property<string>("otmetka_o_broni")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("otmetka_o_oplate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("prodolzhitelnost")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Putevki");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Sotrudniki", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FIO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("Kod_dolzhnosti")
                        .HasColumnType("bigint");

                    b.Property<string>("Pass_dannie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PutevkiID")
                        .HasColumnType("bigint");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vozrast")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("PutevkiID");

                    b.ToTable("Sotrudniki");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Types_of_otdizha", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naimenovanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ogranicheniya")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opisanie")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("PutevkiID")
                        .HasColumnType("bigint");

                    b.HasKey("ID");

                    b.HasIndex("PutevkiID");

                    b.ToTable("Types_of_otdizha");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Dolzhnosti", b =>
                {
                    b.HasOne("Turrist_agent.Moduls.Sotrudniki", null)
                        .WithMany("Dolzhnosti")
                        .HasForeignKey("SotrudnikiID");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Klienti", b =>
                {
                    b.HasOne("Turrist_agent.Moduls.Putevki", null)
                        .WithMany("klienta")
                        .HasForeignKey("PutevkiID");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Sotrudniki", b =>
                {
                    b.HasOne("Turrist_agent.Moduls.Putevki", null)
                        .WithMany("sotrudnika")
                        .HasForeignKey("PutevkiID");
                });

            modelBuilder.Entity("Turrist_agent.Moduls.Types_of_otdizha", b =>
                {
                    b.HasOne("Turrist_agent.Moduls.Putevki", null)
                        .WithMany("vida")
                        .HasForeignKey("PutevkiID");
                });
#pragma warning restore 612, 618
        }
    }
}
